version: 2

sources:
  - name: src_google_ads
    schema: src_google_ads
    tables:
      - name: ads_AdGroupStats_4788955894
      - name: ads_AdGroupConversionStats_4788955894
      - name: ads_AdGroup_4788955894
      - name: ads_AccountBasicStats_4788955894
