version: 2

sources:
  - name: postgres
    schema: postgres
    tables:
      - name: breed
      - name: customer
      - name: pet
      - name: policy
      - name: product
      - name: productline
      - name: subscription
      - name: breed_mapping
      - name: policy_payment
  - name: raw
    schema: raw
    loaded_at_field: cast(run_date as timestamp)
    freshness:
      warn_after: {count: 49, period: hour}
      error_after: {count: 50, period: hour}
      filter: date_diff(cast(run_date as timestamp), current_timestamp(), day) < 2
    tables:
      - name: quoterequest
      - name: renewal
      - name: policy
        description: '{{ doc("raw__policy") }}'
      - name: product
      - name: customer
        description: '{{ doc("raw__customer") }}'
      - name: user
        description: '{{ doc("raw__user") }}'
      - name: pet
        description: '{{ doc("raw__pet") }}'
        columns:
          - name: age_months
            description: This column is deprecated on Django, we should calculate pet age using the pet's date_of_birth column instead.
      - name: breed
      - name: subscription
      - name: vouchercode
      - name: napobenefitcode
      - name: quotewithbenefit
      - name: booking_service_booking
        description: "Puppy Academy booking data"
      - name: booking_service_customer
        description: "Puppy Academy customer data"
      - name: booking_service_subscription
        description: "Puppy Academy subscription data"
      - name: activatedreferral
        description: Referral creation and activation log
      - name: commonbreedmapping
        description: "Breed map sourced from quote-service"
  - name: firestore
    schema: firestore
    description: "Puppy Academy Firebase/Firestore data"
    tables:
      - name: users
      - name: bookings
      - name: email_reminders
      - name: sms_reminders
models:
  - name: stg_raw__policy_ledger
    description: '{{ doc("stg_raw__policy_ledger") }}'