version: 2

sources:
  - name: postgres
    schema: postgres
    tables: 
      - name: breed
      - name: customer
      - name: pet
      - name: policy
        freshness:
          warn_after: {count: 1, period: day}
          error_after: {count: 2, period: day}
        loaded_at_field: fields.created_date
      - name: product
      - name: productline
      - name: subscription
      - name: breed_mapping
      - name: policy_payment
  - name: loss_ratio
    schema: loss_ratio
    tables: 
      - name: all_book_summary
      - name: breed_age_summary
      - name: cohort_summary
      - name: multipet_summary
      - name: product_summary
      - name: species_age_summary
