version: 2

models:
  - name: int_breed_breed_mapping
    description: Joining postgres breed table with breed mappings (breed table has user input values for breed, breed mapping has normalized values)
  - name: int_pet_breed
    description: Combining postgres pet and breeds together
  - name: int_payments
    description: Adding policy_id to payments table for easier purchase_date mapping
  - name: int_policy_subscription
    description: Joins on subscription, policy and payments. Policy ID taken for annual subscriptions from stg_policy and monthly subscriptions taken from int_payments
  - name: int_policy_history
    description: '{{ doc("int_policy_history") }}'
  - name: int_policy_transaction
    description: '{{ doc("int_policy_transaction") }}'
  - name: int_claim_snapshot
    description: Normalized claims data