version: 2

models:
  - name: training_funnel_metrics
    description: "Training & Socialisation funnel metrics aggregated by day."
    columns:
      - name: date
        description: "Aggregation date."
      - name: ad_spend
        description: "Ad spend sourced from growth_sales_by_channel where channel = 'pa_standalone'."
      - name: registrations
        description: "Number of customers in booking-service DB where source = 'pa_registrant'."
      - name: free_trials_started
        description: "Number of free trials started aggregated by day."
      - name: new_annual
        description: "Count of payment intents aggregated by day where payment_plan_type = 'year'."
      - name: new_monthly
        description: "Count of payment intents aggregated by day where payment_plan_type = 'month' and recurring_payment = false."
      - name: recurring_monthly
        description: "Count of payment intents aggregated by day where payment_plan_type = 'month' and recurring_payment = true."
      - name: new_revenue
        description: "Sum of payment amounts aggreated by day where recurring_payment = false."
      - name: recurring_revenue
        description: "Sum of payment amounts aggreated by day where recurring_payment = true."
      - name: other_revenue
        description: "Sum of payment amounts aggreated by day where stripe_customer_id and customer_uuid is null."

  - name: training_user_level_metrics
    description: "Training & Socialisation engagement metrics (cumulative)."
    latest_version: 1
    versions:
      - v: 1
    columns:
      - name: customer_uuid
        description: "Napo internal customer unique identifier."
      - name: email
        description: "Customer email address."
      - name: customer_type
        description: "pa_standalone"
      - name: registration_date
        description: "The date the customer object is created in booking-service DB."
      - name: purchase_date
        description: "The date the customer's Stripe subscription was created."
      - name: subscription_cancel_date
        description: "The date the customer's Stripe subscription was cancelled."
      - name: talk_to_trainer_sessions_booked
        description: "Number of 'call with a trainer' sessions booked"
      - name: sessions_scheduled
        description: "Number of sessions scheduled."
      - name: sessions_joined
        description: "Number of sessions joined."
      - name: sessions_attended
        description: "Number of sessions attended."
      - name: sessions_missed
        description: "Number of sessions missed."
      - name: sessions_cancelled
        description: "Number of sessions cancelled."
      - name: sessions_time_spent
        description: "Cumulative time spent across all sessions (in seconds)."
      - name: classes_scheduled
        description: "Number of classes scheduled, multiple sessions for the same class is only counted once."
      - name: classes_joined
        description: "Number of classes joined, multiple sessions for the same class is only counted once."
      - name: classes_attended
        description: "Number of classes attended, multiple sessions for the same class is only counted once."
      - name: classes_missed
        description: "Number of classes missed, multiple sessions for the same class is only counted once."
      - name: classes_cancelled
        description: "Number of classes cancelled, multiple sessions for the same class is only counted once."
      - name: videos_played
        description: "Total number of videos played (including re-watches)."
      - name: videos_completed
        description: "Total number of videos completed (including re-watches)."
      - name: first_class_attended
        description: "Name of the first class a customer has attended."
      - name: is_training_customer
        description: "Set to true if the customer has purchased a policy with Napo at any point in time."
      - name: is_insurance_customer
        description: "Set to true if the customer can be found in our booking database or via Stripe payments."
