with

    source as (select * from {{ source("src_airbyte", "google_ads_campaign") }}),

    renamed as (

        select
            _airbyte_raw_id,
            _airbyte_extracted_at,
            _airbyte_meta,
            campaign_id,
            metrics_ctr,
            campaign_name,
            segments_date,
            segments_hour,
            metrics_clicks,
            campaign_labels,
            campaign_status,
            campaign_end_date,
            campaign_manual_cpm,
            campaign_manual_cpv,
            campaign_start_date,
            metrics_average_cpc,
            metrics_average_cpm,
            metrics_conversions,
            metrics_cost_micros,
            metrics_impressions,
            metrics_video_views,
            metrics_average_cost,
            metrics_interactions,
            campaign_payment_mode,
            campaign_base_campaign,
            campaign_resource_name,
            campaign_frequency_caps,
            campaign_serving_status,
            metrics_active_view_cpm,
            metrics_active_view_ctr,
            campaign_campaign_budget,
            campaign_experiment_type,
            segments_ad_network_type,
            campaign_bidding_strategy,
            campaign_final_url_suffix,
            metrics_conversions_value,
            campaign_optimization_score,
            metrics_cost_per_conversion,
            metrics_value_per_conversion,
            campaign_budget_amount_micros,
            campaign_bidding_strategy_type,
            campaign_tracking_url_template,
            campaign_url_custom_parameters,
            metrics_active_view_impressions,
            metrics_active_view_viewability,
            metrics_interaction_event_types,
            campaign_target_roas_target_roas,
            metrics_video_quartile_p100_rate,
            campaign_advertising_channel_type,
            metrics_active_view_measurability,
            campaign_accessible_bidding_strategy,
            campaign_app_campaign_setting_app_id,
            campaign_advertising_channel_sub_type,
            campaign_shopping_setting_merchant_id,
            campaign_target_cpa_target_cpa_micros,
            campaign_hotel_setting_hotel_center_id,
            campaign_shopping_setting_enable_local,
            campaign_tracking_setting_tracking_url,
            campaign_ad_serving_optimization_status,
            campaign_app_campaign_setting_app_store,
            campaign_shopping_setting_sales_country,
            campaign_video_brand_safety_suitability,
            campaign_manual_cpc_enhanced_cpc_enabled,
            campaign_target_cpa_cpc_bid_floor_micros,
            campaign_dynamic_search_ads_setting_feeds,
            campaign_percent_cpc_enhanced_cpc_enabled,
            campaign_real_time_bidding_setting_opt_in,
            campaign_target_impression_share_location,
            campaign_target_roas_cpc_bid_floor_micros,
            campaign_target_spend_target_spend_micros,
            campaign_vanity_pharma_vanity_pharma_text,
            campaign_commission_commission_rate_micros,
            campaign_excluded_parent_asset_field_types,
            campaign_target_cpa_cpc_bid_ceiling_micros,
            metrics_active_view_measurable_cost_micros,
            metrics_active_view_measurable_impressions,
            campaign_percent_cpc_cpc_bid_ceiling_micros,
            campaign_shopping_setting_campaign_priority,
            campaign_target_roas_cpc_bid_ceiling_micros,
            campaign_target_spend_cpc_bid_ceiling_micros,
            campaign_maximize_conversion_value_target_roas,
            campaign_network_settings_target_google_search,
            campaign_targeting_setting_target_restrictions,
            campaign_dynamic_search_ads_setting_domain_name,
            campaign_maximize_conversions_target_cpa_micros,
            campaign_network_settings_target_search_network,
            campaign_network_settings_target_content_network,
            campaign_dynamic_search_ads_setting_language_code,
            campaign_selective_optimization_conversion_actions,
            campaign_target_cpm_target_frequency_goal_time_unit,
            campaign_local_campaign_setting_location_source_type,
            campaign_vanity_pharma_vanity_pharma_display_url_mode,
            campaign_target_cpm_target_frequency_goal_target_count,
            campaign_network_settings_target_partner_search_network,
            campaign_target_impression_share_cpc_bid_ceiling_micros,
            campaign_app_campaign_setting_bidding_strategy_goal_type,
            campaign_geo_target_type_setting_negative_geo_target_type,
            campaign_geo_target_type_setting_positive_geo_target_type,
            campaign_target_impression_share_location_fraction_micros,
            campaign_dynamic_search_ads_setting_use_supplied_urls_only,
            campaign_optimization_goal_setting_optimization_goal_types

        from source

    )

select *
from renamed
