
name: 'dbt_napo'
version: '1.0.0'
config-version: 2
profile: 'dbt-napo'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]


target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.

vars:
  # Bing account information, used to filter Airbyte data should the user be added to multiple Bing accounts
  bing_account_id: 'F149C4W5'
  bing_account_name: 'Napo'
  #This is used to increase Conectia's (Affiliate) cost to ensure it matches their export. growth_sales_by_channel has the API's cost * 1+Vat (e.g. 1.2)
  vat_percent: '0.2'
  #The growth_sales_by_channel table will replace the last 30 days of data should marketing/affiliate conversions change with larger lookbacks
  growth_sales_lookback_days: 30

models:
  dbt_napo:
    +persist_docs:
        relation: true
        columns: true
    marts:
      +materialized: table

tests:
  +store_failures: true


