version: 2

models:
  - name: dim_policy_detail
    description: ""
    columns:
      - name: policy_id
        description: ""
        tests:
          - unique
          - not_null
      - name: quote_id
        description: ""

      - name: reference_number
        description: ""

      - name: subscription_active
        description: ""

      - name: created_date
        description: ""

      - name: subscription_created_date
        description: ""

      - name: subscription_modified_date
        description: ""

      - name: start_date
        description: ""

      - name: end_date
        description: ""

      - name: cancel_date
        description: ""

      - name: cancel_reason
        description: ""

      - name: payment_plan_type
        description: ""

      - name: monthly_price
        description: ""

      - name: annual_price
        description: ""

      - name: customer
        description: ""

      - name: pet
        description: ""

      - name: product
        description: ""

      - name: quote_source_reference
        description: ""

      - name: quote_source
        description: ""

      - name: voucher_code
        description: ""

      - name: year_of_birth
        description: ""

      - name: customer_age
        description: ""

      - name: customer_id
        description: ""

      - name: breed_category
        description: ""

      - name: multipet_number
        description: ""

      - name: is_neutered
        description: ""

      - name: age_months
        description: ""

      - name: size
        description: ""

      - name: name
        description: ""

      - name: breed_species
        description: ""

      - name: source
        description: ""

      - name: breed_name
        description: ""

      - name: breed_pk
        description: ""

  - name: fct_active_policies
    description: "A daily snapshot of the current active policies in the table"
    columns:
      - name: active_policies
        description: "All active policies that have an annual payment associated to it, an active subscription associated to it and is not cancelled for all pet types"
      - name: active_puppy_policies_dog_only
        description: "All active dog only policies where the pet age in months is less than or equal to 5 months"
      - name: active_adolescent_policies_dog_only
        description: "All active dog only policies where the pet age in months is more than or equal to 6 months but less than or equal to 25 (pet_age >=6 and pet_age <= 24)"